    const CONFIG=window.PHRASE_COURSE_CONFIG;
    if(!CONFIG)throw new Error("Missing course.config.js");
    const AUDIO_ROOT=CONFIG.audio.root;
    const JP_DISPLAY=CONFIG.readings||{};
    const displayJP=text=>JP_DISPLAY[text]||text;
    const splitChunk=text=>{const value=String(text),match=value.match(/(?:[、。！？,.]|（笑）|（泣）)+$/);return{body:match?value.slice(0,-match[0].length):value,punctuation:match?.[0]||""}};
    const chunkBody=text=>displayJP(splitChunk(text).body);
    const chunkPunctuation=text=>{const punctuation=splitChunk(text).punctuation;return punctuation?`<span class="slot-punctuation" aria-hidden="true">${punctuation}</span>`:""};
    const vocab=CONFIG.vocabulary.map(item=>({...item,wrongMeaning:item.distractorMeaning,image:item.wordImage}));
    const sentences=CONFIG.sentences.map(item=>{const groups=item.chunks.map(chunk=>({...chunk,options:[chunk,chunk.distractor]}));return{...item,groups,distractors:item.reviewDistractors||[groups[1].options[1],groups[2].options[1]]}});
    const stages=[...vocab.flatMap((_,index)=>[{type:"meaning",index},{type:"spellWord",index},{type:"spellPhrase",index}]),...sentences.map((_,index)=>({type:"sentence",index})),...sentences.map((_,index)=>({type:"follow",index}))];
    const startScreen=document.querySelector("#startScreen"),lessonScreen=document.querySelector("#lessonScreen"),finishScreen=document.querySelector("#finishScreen"),stageEl=document.querySelector("#stage"),progressFill=document.querySelector("#progressFill"),progressTrack=document.querySelector("#progressTrack"),jumpOverlay=document.querySelector("#jumpOverlay"),jumpGrid=document.querySelector("#jumpGrid"),lookupPop=document.querySelector("#lookupPop");
    document.title=CONFIG.meta.title;
    document.querySelector("#courseEyebrow").textContent=CONFIG.meta.eyebrow;
    document.querySelector("#courseTitle").textContent=CONFIG.meta.title;
    document.querySelector("#courseDescription").textContent=CONFIG.meta.description;
    document.querySelector("#courseTags").innerHTML=CONFIG.meta.tags.map(tag=>`<span>${tag}</span>`).join("");
    document.querySelector("#courseRoute").innerHTML=CONFIG.meta.route.map(stop=>`<div class="route-stop ${stop.active?"active":""}"><span class="route-circle">${stop.number}</span><span class="route-name">${stop.label}</span></div>`).join("");
    document.querySelector("#finishTitle").textContent=CONFIG.meta.finishTitle;
    document.querySelector("#finishCopy").textContent=CONFIG.meta.finishCopy;
    document.documentElement.style.setProperty("--ink",CONFIG.theme.colors.ink);
    document.documentElement.style.setProperty("--muted",CONFIG.theme.colors.muted);
    document.documentElement.style.setProperty("--blue",CONFIG.theme.colors.primary);
    document.documentElement.style.setProperty("--green",CONFIG.theme.colors.success);
    document.documentElement.style.setProperty("--red",CONFIG.theme.colors.danger);
    document.documentElement.style.setProperty("--orange",CONFIG.theme.colors.accent);
    document.documentElement.style.setProperty("--background-image",`url("${CONFIG.theme.backgroundImage}")`);
    document.documentElement.style.setProperty("--cover-image",`url("${CONFIG.theme.coverImage}")`);
    let stageIndex=0,activeAudio=null,activeAudioResolve=null,activeRepeatTimer=null,activeFeedback=null,lookupTimer=null,oralMode="speech",chunkPlaybackId=0;
    const showScreen=screen=>{[startScreen,lessonScreen,finishScreen].forEach(item=>item.classList.remove("active"));screen.classList.add("active");window.scrollTo(0,0)};
    const audioButton=(path,slow=false,repeat=1)=>`<button class="audio-button ${slow?"slow":""}" type="button" data-audio="${path}" data-slow="${slow}" data-repeat="${repeat}" aria-label="${slow?"慢速":"常速"}播放">${slow?"◷":"▶"}</button>`;
    function stopAudio(){window.clearTimeout(activeRepeatTimer);activeRepeatTimer=null;if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null}if(activeAudioResolve){const resolve=activeAudioResolve;activeAudioResolve=null;resolve(false)}}
    function playAudio(path,slow=false,repeat=1){if(!path)return Promise.resolve(false);stopAudio();return new Promise(resolve=>{let played=0;const finish=completed=>{if(activeAudioResolve!==finish)return;activeAudioResolve=null;activeAudio=null;resolve(completed)};activeAudioResolve=finish;const playOnce=()=>{const audio=new Audio(`${AUDIO_ROOT}${path}`);activeAudio=audio;audio.playbackRate=slow?CONFIG.audio.slowRate:1;audio.onended=()=>{if(activeAudio!==audio)return;played+=1;if(played<repeat)activeRepeatTimer=window.setTimeout(playOnce,170);else finish(true)};audio.onerror=()=>finish(false);audio.play().catch(()=>finish(false))};playOnce()})}
    function playFeedback(result){const path=CONFIG.audio?.[result];if(!path)return;if(activeFeedback){activeFeedback.pause();activeFeedback.currentTime=0}const version=CONFIG.audio.feedbackVersion?`?v=${encodeURIComponent(CONFIG.audio.feedbackVersion)}`:"";activeFeedback=new Audio(`${CONFIG.audio.feedbackRoot||AUDIO_ROOT}${path}${version}`);activeFeedback.play().catch(()=>{})}
    async function playChunkAnswer(path,result){const playbackId=++chunkPlaybackId;playFeedback(result);await new Promise(resolve=>window.setTimeout(resolve,CONFIG.audio.feedbackLeadMs??140));if(playbackId!==chunkPlaybackId)return false;return playAudio(path)}
    function bindAudio(root=stageEl){root.querySelectorAll("[data-audio]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();playAudio(button.dataset.audio,button.dataset.slow==="true",Number(button.dataset.repeat||1))}))}
    function showLookup(target,text){window.clearTimeout(lookupTimer);lookupPop.textContent=text;const rect=target.getBoundingClientRect();lookupPop.style.left=`${Math.max(58,Math.min(window.innerWidth-58,rect.left+rect.width/2))}px`;lookupPop.style.top=`${Math.max(45,rect.top)}px`;lookupPop.classList.add("visible");lookupTimer=window.setTimeout(()=>lookupPop.classList.remove("visible"),1350)}
    function bindLookups(root=stageEl){root.querySelectorAll("[data-lookup]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();showLookup(button,button.dataset.lookup);if(button.dataset.lookupAudio)playAudio(button.dataset.lookupAudio)}))}
    const sceneCard=(image,caption,audio)=>`<article class="scene-card"><img src="${image}" alt="与${caption}对应的主题场景"><div class="scene-audio">${audioButton(audio)}${audioButton(audio,true)}</div><div class="scene-caption">${caption}</div></article>`;
    const explanationHTML=(lines,audio,grammar=false)=>`<section class="explanation ${grammar?"grammar":""}"><div class="explanation-label">${grammar?"句子语法讲解":"词汇讲解"}</div><ul>${lines.map(line=>`<li>${line}</li>`).join("")}</ul>${grammar?"":`<button class="explain-audio" type="button" data-audio="${audio}" data-repeat="2" aria-label="播放两遍">▶</button>`}</section>`;
    const completeHTML=(parts,audio,explanation=[],grammar=false)=>`<div class="complete"><div class="complete-sentence"><div class="complete-audio">${audioButton(audio)}${audioButton(audio,true)}</div><div class="complete-copy"><div class="complete-japanese">${parts.map(part=>{const punctuation=splitChunk(part.jp).punctuation;return`<button class="complete-token" type="button" data-lookup="${part.zh}" data-lookup-audio="${part.audio}" aria-label="${part.jp}"><span>${chunkBody(part.jp)}</span></button>${punctuation?`<span class="complete-punctuation">${punctuation}</span>`:""}`}).join("")}</div></div></div>${explanation.length?explanationHTML(explanation,audio,grammar):""}<button class="continue-button" type="button" data-next>继续</button></div>`;
    const wireContinue=()=>stageEl.querySelector("[data-next]")?.addEventListener("click",nextStage);

    function renderMeaning(index){
      const item=vocab[index],options=Math.random()>.5?[item.meaning,item.wrongMeaning]:[item.wrongMeaning,item.meaning];
      stageEl.innerHTML=`${sceneCard(item.image,item.meaning,item.wordAudio)}<section class="board"><p class="stem"><strong>${displayJP(item.word)}</strong> 在这里的意思是：</p><div class="choice-list">${options.map(option=>`<button class="choice" type="button" data-answer="${option}">${option}</button>`).join("")}</div></section>`;bindAudio();playAudio(item.wordAudio);
      stageEl.querySelectorAll("[data-answer]").forEach(button=>button.addEventListener("click",()=>{if(button.dataset.answer!==item.meaning){playFeedback("wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");window.setTimeout(()=>button.classList.remove("wrong"),480);return}playFeedback("correct");button.classList.add("correct");stageEl.querySelectorAll("[data-answer]").forEach(choice=>choice.disabled=true);window.setTimeout(()=>{stageEl.querySelector(".board").innerHTML=`<p class="stem"><strong>${displayJP(item.word)}</strong>：${item.meaning}</p>${explanationHTML(item.wordExplanation,item.wordAudio)}<button class="continue-button" type="button" data-next>继续</button>`;bindAudio();wireContinue()},420)}));
    }

    function renderSpelling(item,mode){
      const isWord=mode==="word",parts=isWord?item.wordChunks:item.phraseChunks,translation=isWord?item.meaning:item.phraseMeaning,audio=isWord?item.wordAudio:item.phraseAudio,image=isWord?item.image:item.phraseImage,explanation=isWord?[]:item.phraseExplanation,optionOrder=[...parts].sort(()=>Math.random()-.5),slots=parts.map(()=>null);let current=0;
      const draw=(complete=false)=>{const board=complete?`<section class="board">${completeHTML(parts,audio,explanation)}</section>`:`<section class="board"><p class="stem">请翻译：</p><div class="audio-line">${audioButton(audio)}<span class="audio-divider"></span>${audioButton(audio,true)}</div><div class="slots">${parts.map((part,index)=>`<div class="slot ${part.wide?"wide":""} ${slots[index]?"correct":""}">${slots[index]?`<button class="slot-button" type="button" data-lookup="${part.zh}" data-lookup-audio="${part.audio}" aria-label="${part.jp}"><span>${displayJP(part.jp)}</span></button>`:""}</div>`).join("")}</div><div class="pool">${optionOrder.map(part=>`<button class="pill ${part.wide?"wide":""} ${slots.includes(part)?"used":""}" type="button" data-option-index="${parts.indexOf(part)}" aria-label="${part.jp}"><span>${displayJP(part.jp)}</span></button>`).join("")}</div></section>`;stageEl.innerHTML=`${sceneCard(image,translation,audio)}${board}`;bindAudio();bindLookups();if(complete){playAudio(audio);wireContinue();return}stageEl.querySelectorAll("[data-option-index]").forEach(button=>button.addEventListener("click",async()=>{const part=parts[Number(button.dataset.optionIndex)];showLookup(button,part.zh);if(part!==parts[current]){playChunkAnswer(part.audio,"wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");window.setTimeout(()=>button.classList.remove("wrong"),520);return}stageEl.querySelectorAll("[data-option-index]").forEach(option=>option.disabled=true);slots[current]=part;button.classList.add("correct");current+=1;await playChunkAnswer(part.audio,"correct");draw(current===parts.length)}))};draw();playAudio(audio);
    }

    const promptHTML=groups=>`<div class="topic-card">${groups.map(group=>`<button class="lookup" type="button" data-lookup="${group.jp}" data-lookup-audio="${group.audio}">${group.zh}</button>`).join("")}</div>`;
    function renderSentence(index){
      const item=sentences[index],chosen=item.groups.map(()=>null),optionOrders=item.groups.map(group=>Math.random()>.5?group.options:[...group.options].reverse());let current=0;
      const draw=(complete=false)=>{if(complete){stageEl.innerHTML=`<section class="board" style="margin-top:2px">${promptHTML(item.groups)}${completeHTML(item.groups,item.audio,item.explanation,true)}</section>`;bindAudio();bindLookups();playAudio(item.audio);wireContinue();return}const active=item.groups[current];stageEl.innerHTML=`<section class="board" style="margin-top:2px">${promptHTML(item.groups)}<div class="slots">${item.groups.map((group,groupIndex)=>`<div class="slot-unit"><div class="slot ${group.wide?"wide":""} ${chosen[groupIndex]?"correct":""}">${chosen[groupIndex]?`<button class="slot-button" type="button" data-lookup="${group.zh}" data-lookup-audio="${group.audio}" aria-label="${group.jp}"><span>${chunkBody(group.jp)}</span></button>`:`<span class="slot-hint">${group.zh}</span>`}</div>${chunkPunctuation(group.jp)}</div>`).join("")}</div><div class="two-choice">${optionOrders[current].map(option=>`<button class="pill ${option.wide?"wide":""}" type="button" data-sentence-option="${active.options.indexOf(option)}" aria-label="${option.jp}"><span>${chunkBody(option.jp)}</span></button>`).join("")}</div></section>`;bindLookups();stageEl.querySelectorAll("[data-sentence-option]").forEach(button=>button.addEventListener("click",async()=>{const option=active.options[Number(button.dataset.sentenceOption)];showLookup(button,option.zh);if(option.jp!==active.jp){playChunkAnswer(option.audio,"wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");window.setTimeout(()=>button.classList.remove("wrong"),520);return}stageEl.querySelectorAll("[data-sentence-option]").forEach(choice=>choice.disabled=true);chosen[current]=active;button.classList.add("correct");current+=1;await playChunkAnswer(option.audio,"correct");draw(current===item.groups.length)}))};draw();
    }
    function renderOralFallback(index){
      const item=sentences[index],options=[...item.groups,...item.distractors].sort(()=>Math.random()-.5),selected=item.groups.map(()=>null);let current=0;
      const draw=(complete=false)=>{if(complete){stageEl.innerHTML=`<section class="board" style="margin-top:2px">${promptHTML(item.groups)}${completeHTML(item.groups,item.audio)}</section>`;bindAudio();bindLookups();wireContinue();return}stageEl.innerHTML=`<section class="board" style="margin-top:2px">${promptHTML(item.groups)}<p class="stem">请拼写句子：</p><div class="slots">${item.groups.map((group,groupIndex)=>`<div class="slot-unit"><div class="slot ${group.wide?"wide":""} ${selected[groupIndex]?"correct":""}">${selected[groupIndex]?`<button class="slot-button" type="button" data-lookup="${group.zh}" data-lookup-audio="${group.audio}" aria-label="${group.jp}"><span>${chunkBody(group.jp)}</span></button>`:`<span class="slot-hint">${group.zh}</span>`}</div>${chunkPunctuation(group.jp)}</div>`).join("")}</div><div class="pool review-pool">${options.map((option,optionIndex)=>`<button class="pill ${option.wide?"wide":""} ${selected.includes(option)?"used":""}" type="button" data-review-index="${optionIndex}" aria-label="${option.jp}"><span>${chunkBody(option.jp)}</span></button>`).join("")}</div></section>`;bindLookups();stageEl.querySelectorAll("[data-review-index]").forEach(button=>button.addEventListener("click",async()=>{const option=options[Number(button.dataset.reviewIndex)];showLookup(button,option.zh);if(option.jp!==item.groups[current].jp){playChunkAnswer(option.audio,"wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");window.setTimeout(()=>button.classList.remove("wrong"),560);return}stageEl.querySelectorAll("[data-review-index]").forEach(choice=>choice.disabled=true);selected[current]=option;button.classList.add("correct");current+=1;await playChunkAnswer(option.audio,"correct");draw(current===item.groups.length)}))};draw();
    }
    const escapeHTML=text=>String(text).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
    const speechText=text=>String(text).replace(/[\s、。！？,.（）()「」『』笑泣]/g,"");
    function speechScore(expected,actual){const left=speechText(expected),right=speechText(actual);if(!left||!right)return null;const row=Array.from({length:right.length+1},(_,index)=>index);for(let i=1;i<=left.length;i+=1){let previous=row[0];row[0]=i;for(let j=1;j<=right.length;j+=1){const saved=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(left[i-1]===right[j-1]?0:1));previous=saved}}return Math.max(0,Math.round((1-row[right.length]/Math.max(left.length,right.length))*100))}
    function renderFollow(index){
      const item=sentences[index],Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
      let transcript="",recognition=null,timerId=null,startedAt=0,elapsed=0,autoPlayed=false,oralError="",settled=false;
      const targetHTML=()=>item.groups.map(group=>`${chunkBody(group.jp)}${splitChunk(group.jp).punctuation}`).join("");
      const stopRecording=()=>{window.clearInterval(timerId);timerId=null;if(recognition){try{recognition.stop()}catch{}}};
      const drawRecord=(state="idle")=>{
        const score=transcript?speechScore(item.jp,transcript):null,passed=score!==null&&score>=CONFIG.audio.passScore;
        const result=state==="done"?`<div class="oral-result ${passed?"correct":"wrong"}"><div class="oral-verdict">${passed?"发音正确":"发音还不太对"}</div><div class="oral-transcript">识别结果：${transcript?escapeHTML(transcript):"未识别到有效语音"}</div>${score!==null?`<div class="oral-score">匹配度 ${score}%</div>`:""}</div>${passed?"":`<button class="oral-retry" type="button" data-retry>重新朗读</button>`}`:"";
        const error=state==="error"?`<div class="oral-error">${oralError}</div><button class="oral-retry" type="button" data-retry>重新尝试</button>`:"";
        stageEl.innerHTML=`<section class="board" style="margin-top:2px"><div class="follow-card"><p class="follow-title">请跟读：</p><div class="audio-line" style="justify-content:center;margin-top:0">${audioButton(item.audio)}<span class="audio-divider"></span>${audioButton(item.audio,true)}</div><div class="follow-target">${targetHTML()}</div><div class="follow-translation">${item.zh}</div></div>${state==="idle"||state==="recording"?`<div class="record-area"><button class="record-button ${state==="recording"?"recording":""}" type="button" data-record aria-label="${state==="recording"?"停止录音":"开始录音"}">${state==="recording"?"■":"●"}</button><div class="record-copy">${state==="recording"?"点击结束":"点击录音"}</div>${state==="recording"?`<div class="record-timer" data-record-timer>${elapsed.toFixed(1)}s</div>`:""}</div>`:""}${result}${error}${state==="idle"?`<button class="skip-button" type="button" data-skip>现在不做口语题</button>`:""}</section>`;
        bindAudio();
        if(state==="idle"&&!autoPlayed){autoPlayed=true;playAudio(item.audio)}
        stageEl.querySelector("[data-record]")?.addEventListener("click",()=>state==="recording"?stopRecording():startRecording());
        stageEl.querySelector("[data-retry]")?.addEventListener("click",()=>{transcript="";elapsed=0;settled=false;drawRecord("idle")});
        stageEl.querySelector("[data-skip]")?.addEventListener("click",()=>{oralMode="chunks";stopRecording();stopAudio();renderOralFallback(index)});
        if(state==="done"){playFeedback(passed?"correct":"wrong");if(passed)window.setTimeout(nextStage,850)}
      };
      async function startRecording(){
        if(!Recognition){oralError="当前浏览器不支持日语语音识别，请使用 Chrome 或 Edge 打开本页。";drawRecord("error");return}
        stopAudio();
        transcript="";settled=false;recognition=new Recognition();recognition.lang="ja-JP";recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=3;
        recognition.onresult=event=>{transcript=Array.from(event.results).map(result=>result[0].transcript).join("")};
        recognition.onerror=event=>{if(settled)return;settled=true;window.clearInterval(timerId);timerId=null;oralError=event.error==="not-allowed"?"麦克风权限被拒绝了，请允许权限后重试。":"没有识别到有效语音，请靠近麦克风再试一次。";drawRecord("error")};
        recognition.onend=()=>{if(settled)return;settled=true;window.clearInterval(timerId);timerId=null;drawRecord("done")};
        try{elapsed=0;startedAt=Date.now();recognition.start();drawRecord("recording");timerId=window.setInterval(()=>{elapsed=(Date.now()-startedAt)/1000;const timer=stageEl.querySelector("[data-record-timer]");if(timer)timer.textContent=`${elapsed.toFixed(1)}s`;if(elapsed>=15)stopRecording()},100)}catch{oralError="无法启动语音识别，请刷新页面后重试。";drawRecord("error")}
      }
      drawRecord();
    }
    function nextStage(){stageIndex+=1;if(stageIndex>=stages.length){showScreen(finishScreen);return}renderStage()}
    function renderStage(){window.scrollTo(0,0);lookupPop.classList.remove("visible");const current=stages[stageIndex];progressFill.style.width=`${(stageIndex+1)/stages.length*100}%`;if(current.type==="meaning")renderMeaning(current.index);if(current.type==="spellWord")renderSpelling(vocab[current.index],"word");if(current.type==="spellPhrase")renderSpelling(vocab[current.index],"phrase");if(current.type==="sentence")renderSentence(current.index);if(current.type==="follow")(oralMode==="chunks"?renderOralFallback:renderFollow)(current.index)}
    function openJumpPicker(){jumpGrid.innerHTML=stages.map((_,index)=>`<button class="jump-option ${index===stageIndex?"selected":""}" type="button" data-jump-index="${index}">${index+1}</button>`).join("");jumpOverlay.hidden=false;jumpGrid.querySelectorAll("[data-jump-index]").forEach(button=>button.addEventListener("click",()=>{stopAudio();stageIndex=Number(button.dataset.jumpIndex);jumpOverlay.hidden=true;renderStage()}))}
    document.querySelector("#startButton").addEventListener("click",()=>{stageIndex=0;oralMode="speech";renderStage();showScreen(lessonScreen)});document.querySelector("#closeButton").addEventListener("click",()=>showScreen(startScreen));document.querySelector("#restartButton").addEventListener("click",()=>{stageIndex=0;oralMode="speech";renderStage();showScreen(lessonScreen)});progressTrack.addEventListener("click",openJumpPicker);document.querySelector("#jumpClose").addEventListener("click",()=>{jumpOverlay.hidden=true});jumpOverlay.addEventListener("click",event=>{if(event.target===jumpOverlay)jumpOverlay.hidden=true});
