    const CONFIG=window.PHRASE_COURSE_CONFIG;
    if(!CONFIG)throw new Error("Missing course.config.js");
    const AUDIO_ROOT=CONFIG.audio.root;
    const JP_DISPLAY=CONFIG.readings||{};
    // Keep the configured readings for kanji compounds, then annotate every
    // remaining Japanese run (including words written entirely in kana). This
    // makes both kana and romaji modes consistent across every rendered text.
    const READING_BY_BASE={};
    Object.values(JP_DISPLAY).forEach(html=>String(html).replace(/<ruby>([^<]+)<rt>([^<]+)<\/rt><\/ruby>/g,(_,base,reading)=>{READING_BY_BASE[base]=reading;return _}));
    const annotatePlainJP=value=>String(value).replace(/[ぁ-ゖァ-ヺー]+|[一-龯々]+/g,run=>{
      const reading=READING_BY_BASE[run];
      if(reading)return `<ruby>${run}<rt>${reading}</rt></ruby>`;
      if(/^[ぁ-ゖァ-ヺー]+$/.test(run))return `<ruby>${run}<rt>${run.replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-0x60))}</rt></ruby>`;
      return run.split("").map(char=>READING_BY_BASE[char]?`<ruby>${char}<rt>${READING_BY_BASE[char]}</rt></ruby>`:char).join("");
    });
    const displayJP=text=>{
      const mapped=String(JP_DISPLAY[text]||String(text)).replace(/<ruby>([^<]+)(?:<rt>([^<]+)<\/rt>)?<\/ruby>/g,(_,base,reading)=>`<ruby>${base}<rt>${reading||READING_BY_BASE[base]||(/^[ぁ-ゖァ-ヺー]+$/.test(base)?base.replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-0x60)):"")}</rt></ruby>`);
      const rubyBlocks=[];
      const protectedHTML=mapped.replace(/<ruby>[\s\S]*?<\/ruby>/g,block=>{rubyBlocks.push(block);return `\u0000${rubyBlocks.length-1}\u0000`});
      const annotated=annotatePlainJP(protectedHTML);
      return annotated.replace(/\u0000(\d+)\u0000/g,(_,index)=>rubyBlocks[Number(index)]);
    };
    const splitChunk=text=>{const value=String(text),match=value.match(/(?:[、。！？,.]|（笑）|（泣）)+$/);return{body:match?value.slice(0,-match[0].length):value,punctuation:match?.[0]||""}};
    const chunkBody=text=>displayJP(splitChunk(text).body);
    const chunkPunctuation=text=>{const punctuation=splitChunk(text).punctuation;return punctuation?`<span class="slot-punctuation" aria-hidden="true">${punctuation}</span>`:""};
    const vocab=CONFIG.vocabulary.map(item=>({...item,wrongMeaning:item.distractorMeaning,image:item.wordImage}));
    const sentences=CONFIG.sentences.map(item=>{const groups=item.chunks.map(chunk=>({...chunk,options:[chunk,chunk.distractor]}));return{...item,groups,distractors:item.reviewDistractors||[groups[1].options[1],groups[2].options[1]]}});
    const stages=[...vocab.flatMap((_,index)=>[{type:"meaning",index},{type:"spellWord",index},{type:"spellPhrase",index}]),...sentences.map((_,index)=>({type:"sentence",index})),...sentences.map((_,index)=>({type:"follow",index}))];
    const startScreen=document.querySelector("#startScreen"),lessonScreen=document.querySelector("#lessonScreen"),finishScreen=document.querySelector("#finishScreen"),stageEl=document.querySelector("#stage"),progressFill=document.querySelector("#progressFill"),progressTrack=document.querySelector("#progressTrack"),jumpOverlay=document.querySelector("#jumpOverlay"),jumpGrid=document.querySelector("#jumpGrid"),lookupPop=document.querySelector("#lookupPop");
    document.title=CONFIG.meta.title;
    document.querySelector("#courseEyebrow").textContent=CONFIG.meta.eyebrow;
    document.querySelector("#courseTitle").textContent=CONFIG.meta.title;
    document.querySelector("#courseDescription").textContent=CONFIG.meta.description;
    document.querySelector("#courseTags").innerHTML=CONFIG.meta.tags.map(tag=>`<span>${tag}</span>`).join("");
    document.querySelector("#courseRoute").innerHTML=CONFIG.meta.route.map(stop=>`<div class="route-stop ${stop.active?"active":""}"><span class="route-circle">${stop.number}</span><span class="route-name">${stop.label}</span></div>`).join("");
    document.querySelector("#finishTitle").textContent=CONFIG.meta.finishTitle;
    document.querySelector("#finishCopy").textContent=CONFIG.meta.finishCopy;
    document.documentElement.style.setProperty("--ink",CONFIG.theme.colors.ink);
    document.documentElement.style.setProperty("--muted",CONFIG.theme.colors.muted);
    document.documentElement.style.setProperty("--blue",CONFIG.theme.colors.primary);
    document.documentElement.style.setProperty("--green",CONFIG.theme.colors.success);
    document.documentElement.style.setProperty("--red",CONFIG.theme.colors.danger);
    document.documentElement.style.setProperty("--orange",CONFIG.theme.colors.accent);
    document.documentElement.style.setProperty("--background-image",`url("${CONFIG.theme.backgroundImage}")`);
    document.documentElement.style.setProperty("--cover-image",`url("${CONFIG.theme.coverImage}")`);
    let stageIndex=0,activeAudio=null,activeAudioResolve=null,activeRepeatTimer=null,activeFeedback=null,lookupTimer=null,oralMode="speech",chunkPlaybackId=0,stageVersion=0,activeRecognition=null,activeRecordTimer=null;
    const stageTimers=new Set();
    const showScreen=screen=>{[startScreen,lessonScreen,finishScreen].forEach(item=>item.classList.remove("active"));screen.classList.add("active");window.scrollTo(0,0)};
    const audioButton=(path,slow=false,repeat=1,voice="machine")=>`<button class="audio-button ${slow?"slow":""}" type="button" data-audio="${path}" data-voice="${voice}" data-slow="${slow}" data-repeat="${repeat}" aria-label="${slow?"慢速":"常速"}播放">${slow?"◷":"▶"}</button>`;
    function stopAudio(){window.clearTimeout(activeRepeatTimer);activeRepeatTimer=null;if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null}if(activeAudioResolve){const resolve=activeAudioResolve;activeAudioResolve=null;resolve(false)}}
    function playAudio(path,slow=false,repeat=1,voice="machine"){if(!path)return Promise.resolve(false);stopAudio();return new Promise(resolve=>{let played=0;const finish=completed=>{if(activeAudioResolve!==finish)return;activeAudioResolve=null;activeAudio=null;resolve(completed)};activeAudioResolve=finish;const playOnce=()=>{const roots={machine:AUDIO_ROOT,npc:CONFIG.audio.npcRoot||AUDIO_ROOT,actor:CONFIG.audio.actorRoot||AUDIO_ROOT};const audio=new Audio(`${roots[voice]||AUDIO_ROOT}${path}`);activeAudio=audio;audio.playbackRate=slow?CONFIG.audio.slowRate:1;audio.onended=()=>{if(activeAudio!==audio)return;played+=1;if(played<repeat)activeRepeatTimer=window.setTimeout(playOnce,170);else finish(true)};audio.onerror=()=>finish(false);audio.play().catch(()=>finish(false))};playOnce()})}
    function playFeedback(result){const path=CONFIG.audio?.[result];if(!path)return;if(activeFeedback){activeFeedback.pause();activeFeedback.currentTime=0}const version=CONFIG.audio.feedbackVersion?`?v=${encodeURIComponent(CONFIG.audio.feedbackVersion)}`:"";activeFeedback=new Audio(`${CONFIG.audio.feedbackRoot||AUDIO_ROOT}${path}${version}`);activeFeedback.play().catch(()=>{})}
    async function playChunkAnswer(path,result){const playbackId=++chunkPlaybackId;stopAudio();playFeedback(result);await new Promise(resolve=>window.setTimeout(resolve,CONFIG.audio.feedbackLeadMs??140));if(playbackId!==chunkPlaybackId)return false;return playAudio(path)}
    function bindAudio(root=stageEl){root.querySelectorAll("[data-audio]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();playAudio(button.dataset.audio,button.dataset.slow==="true",Number(button.dataset.repeat||1),button.dataset.voice||"machine")}))}
    function showLookup(target,text){window.clearTimeout(lookupTimer);lookupPop.textContent=text;const rect=target.getBoundingClientRect();lookupPop.style.left=`${Math.max(58,Math.min(window.innerWidth-58,rect.left+rect.width/2))}px`;lookupPop.style.top=`${Math.max(45,rect.top)}px`;lookupPop.classList.add("visible");lookupTimer=window.setTimeout(()=>lookupPop.classList.remove("visible"),1350)}
    function bindLookups(root=stageEl){root.querySelectorAll("[data-lookup]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();showLookup(button,button.dataset.lookup);if(button.dataset.lookupAudio)playAudio(button.dataset.lookupAudio,false,1,button.dataset.lookupVoice||"machine")}))}
    const sceneData=CONFIG.theme.scene||{};
    const sentenceForVocabulary=id=>sentences.find(sentence=>sentence.sourceVocabularyId===id)||null;
    const sceneBackdrop=(sentence=null,showDialogue=true,stageType="build")=>{const registry=sceneData.characters||{},shopkeeperId=sceneData.shopkeeperId,shopkeeper=registry[shopkeeperId],customerId=stageType==="follow"?sentence?.followCustomerId:sentence?.buildCustomerId,customer=registry[customerId],dialogue=sentence?.dialogue||sceneData.dialogue,audio=dialogue?.audio||"";const dialogueHTML=showDialogue&&dialogue?.jp?`<div class="scene-prompt">${audio?audioButton(audio,false,1,"npc"):""}<div class="scene-dialogue-groups">${(dialogue.groups||[{jp:dialogue.jp,zh:dialogue.zh}]).map(group=>`<button class="scene-dialogue-text lookup" type="button" data-lookup="${group.zh||""}" data-lookup-audio="${group.audio||""}" data-lookup-voice="machine">${displayJP(group.jp)}</button>`).join("")}</div></div>`:"";const characters=[shopkeeper&&{...shopkeeper,id:shopkeeperId,side:"left"},customer&&{...customer,id:customerId,side:"right"}].filter(Boolean);return`<section class="scene-backdrop conversation-scene" style="--scene-image:url('${sceneData.backgroundImage||CONFIG.theme.backgroundImage}')">${dialogueHTML}${characters.map(character=>`<div class="scene-character ${character.side} npc-${character.id}"><img class="scene-npc" src="${character.image}" alt="${character.name||"NPC"}"></div>`).join("")}</section>`};
    const sceneCard=(image,caption,audio,sentence=null,voice="npc")=>`<article class="scene-card"><img src="${image}" alt="${caption}对应的主题场景"><div class="scene-audio">${audioButton(audio,false,1,voice)}${audioButton(audio,true,1,voice)}</div><div class="scene-caption">${sentence?sentence.groups.map(group=>`<button class="scene-caption-chunk lookup" type="button" data-lookup="${group.zh}" data-lookup-audio="${group.audio}" data-lookup-voice="machine">${displayJP(group.jp)}</button>`).join(""):displayJP(caption)}</div></article>`;
    const explanationHTML=(lines,audio,grammar=false,voice="machine")=>`<section class="explanation ${grammar?"grammar":""}"><div class="explanation-label">${grammar?"句子语法讲解":"词汇讲解"}</div><ul>${lines.map(line=>`<li>${line}</li>`).join("")}</ul>${grammar?"":`<button class="explain-audio" type="button" data-audio="${audio}" data-voice="${voice}" data-repeat="2" aria-label="播放两遍">▶</button>`}</section>`;
    const completeHTML=(parts,audio,explanation=[],grammar=false,voice="npc")=>`<div class="complete"><div class="complete-sentence"><div class="complete-audio">${audioButton(audio,false,1,voice)}${audioButton(audio,true,1,voice)}</div><div class="complete-copy"><div class="complete-japanese">${parts.map(part=>{const punctuation=splitChunk(part.jp).punctuation;return`<button class="complete-token" type="button" data-lookup="${part.zh}" data-lookup-audio="${part.audio}" data-lookup-voice="machine" aria-label="${part.jp}"><span>${chunkBody(part.jp)}</span></button>${punctuation?`<span class="complete-punctuation">${punctuation}</span>`:""}`}).join("")}</div></div></div>${explanation.length?explanationHTML(explanation,audio,grammar,voice):""}<button class="continue-button" type="button" data-next>继续</button></div>`;
    const wireContinue=()=>stageEl.querySelector("[data-next]")?.addEventListener("click",nextStage);
    const scheduleStage=(callback,delay,version=stageVersion)=>{const timer=window.setTimeout(()=>{stageTimers.delete(timer);if(version===stageVersion)callback()},delay);stageTimers.add(timer);return timer};
    function clearStageActivity(){stageVersion+=1;chunkPlaybackId+=1;stopAudio();stageTimers.forEach(timer=>window.clearTimeout(timer));stageTimers.clear();window.clearInterval(activeRecordTimer);activeRecordTimer=null;if(activeRecognition){activeRecognition.onresult=null;activeRecognition.onerror=null;activeRecognition.onend=null;try{activeRecognition.abort()}catch{}activeRecognition=null}if(activeFeedback){activeFeedback.pause();activeFeedback.currentTime=0;activeFeedback=null}window.clearTimeout(lookupTimer);lookupPop.classList.remove("visible")}

    function renderMeaning(index){
      const item=vocab[index],options=Math.random()>.5?[item.meaning,item.wrongMeaning]:[item.wrongMeaning,item.meaning];
      const sentence=sentenceForVocabulary(item.id),exposureVoice=sentence?.exposureVoice||"actor";stageEl.innerHTML=`${sceneCard(item.image,sentence?.jp||item.word,sentence?.exposureAudio||item.wordAudio,sentence,exposureVoice)}<section class="board"><p class="stem stem-with-audio"><span class="stem-audio">${audioButton(item.wordAudio,false,1,"machine")}</span><strong>${displayJP(item.word)}</strong><span>在这里的意思是：</span></p><div class="choice-list">${options.map(option=>`<button class="choice" type="button" data-answer="${option}">${option}</button>`).join("")}</div></section>`;bindAudio();bindLookups();playAudio(sentence?.exposureAudio||item.wordAudio,false,1,sentence?.exposureAudio?exposureVoice:"machine");
      const version=stageVersion;stageEl.querySelectorAll("[data-answer]").forEach(button=>button.addEventListener("click",()=>{if(button.dataset.answer!==item.meaning){playFeedback("wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");scheduleStage(()=>button.classList.remove("wrong"),480,version);return}playFeedback("correct");button.classList.add("correct");stageEl.querySelectorAll("[data-answer]").forEach(choice=>choice.disabled=true);scheduleStage(()=>{stageEl.querySelector(".board").innerHTML=`<p class="stem"><strong>${displayJP(item.word)}</strong>：${item.meaning}</p>${explanationHTML(item.wordExplanation,item.wordAudio)}<button class="continue-button" type="button" data-next>继续</button>`;bindAudio();wireContinue()},420,version)}));
    }

    function renderSpelling(item,mode){
      const isWord=mode==="word",parts=isWord?item.wordChunks:item.phraseChunks,translation=isWord?item.meaning:item.phraseMeaning,audio=isWord?item.wordAudio:item.phraseAudio,image=isWord?item.image:item.phraseImage,explanation=isWord?[]:item.phraseExplanation,optionOrder=[...parts].sort(()=>Math.random()-.5),slots=parts.map(()=>null);let current=0;
      const sentence=sentenceForVocabulary(item.id),version=stageVersion;const imageSentence=isWord?sentence:null;const imageCaption=isWord?(sentence?.jp||item.word):item.phrase;const imageAudio=isWord?(sentence?.exposureAudio||item.wordAudio):audio;const imageVoice=isWord&&sentence?.exposureAudio?(sentence.exposureVoice||"actor"):"machine";const draw=(complete=false)=>{const board=complete?`<section class="board">${completeHTML(parts,audio,explanation,false,"machine")}</section>`:`<section class="board"><p class="stem">请翻译：</p><div class="audio-line">${audioButton(audio,false,1,"machine")}<span class="audio-divider"></span>${audioButton(audio,true,1,"machine")}</div><div class="slots">${parts.map((part,index)=>`<div class="slot ${part.wide?"wide":""} ${slots[index]?"correct":""}">${slots[index]?`<button class="slot-button" type="button" data-lookup="${part.zh}" data-lookup-audio="${part.audio}" data-lookup-voice="machine" aria-label="${part.jp}"><span>${displayJP(part.jp)}</span></button>`:""}</div>`).join("")}</div><div class="pool">${optionOrder.map(part=>`<button class="pill ${part.wide?"wide":""} ${slots.includes(part)?"used":""}" type="button" data-option-index="${parts.indexOf(part)}" aria-label="${part.jp}"><span>${displayJP(part.jp)}</span></button>`).join("")}</div></section>`;stageEl.innerHTML=`${sceneCard(image,imageCaption,imageAudio,imageSentence,imageVoice)}${board}`;bindAudio();bindLookups();if(complete){wireContinue();return}stageEl.querySelectorAll("[data-option-index]").forEach(button=>button.addEventListener("click",()=>{const part=parts[Number(button.dataset.optionIndex)];if(part!==parts[current]){void playChunkAnswer(part.audio,"wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");scheduleStage(()=>button.classList.remove("wrong"),520,version);return}slots[current]=part;current+=1;const completeNow=current===parts.length;const playback=playChunkAnswer(part.audio,"correct");draw(completeNow);if(completeNow)void playback.then(completed=>{if(completed&&version===stageVersion)playAudio(audio,false,1,"machine")})}))};draw();playAudio(audio,false,1,"machine");
    }

    const promptHTML=groups=>`<div class="topic-card">${groups.map(group=>`<button class="lookup" type="button" data-lookup="${group.jp}" data-lookup-audio="${group.audio}">${group.zh}</button>`).join("")}</div>`;
    function renderSentence(index){
      const item=sentences[index],chosen=item.groups.map(()=>null),optionOrders=item.groups.map(group=>Math.random()>.5?group.options:[...group.options].reverse());let current=0;
      const version=stageVersion,targetAudio=item.buildAudio;const draw=(complete=false,showDialogue=item.dialoguePosition!=="after")=>{if(complete){stageEl.innerHTML=`${sceneBackdrop(item,showDialogue,"build")}<section class="board" style="margin-top:2px">${completeHTML(item.groups,targetAudio,item.explanation,true,"npc")}</section>`;bindAudio();bindLookups();wireContinue();return}const active=item.groups[current];stageEl.innerHTML=`${sceneBackdrop(item,showDialogue,"build")}<section class="board sentence-board" style="margin-top:2px"><p class="sentence-instruction">选择日语 chunk，完成中文提示：</p><div class="slots">${item.groups.map((group,groupIndex)=>`<div class="slot-unit"><div class="slot ${group.wide?"wide":""} ${chosen[groupIndex]?"correct":""}">${chosen[groupIndex]?`<button class="slot-button" type="button" data-lookup="${group.zh}" data-lookup-audio="${group.audio}" data-lookup-voice="machine" aria-label="${group.jp}"><span>${chunkBody(group.jp)}</span></button>`:`<button class="slot-hint lookup" type="button" data-lookup="${group.jp}" data-lookup-audio="${group.audio}" data-lookup-voice="machine">${group.zh}</button>`}</div>${chunkPunctuation(group.jp)}</div>`).join("")}</div><div class="two-choice">${optionOrders[current].map(option=>`<button class="pill ${option.wide?"wide":""}" type="button" data-sentence-option="${active.options.indexOf(option)}" aria-label="${option.jp}"><span>${chunkBody(option.jp)}</span></button>`).join("")}</div></section>`;bindAudio();bindLookups();stageEl.querySelectorAll("[data-sentence-option]").forEach(button=>button.addEventListener("click",()=>{const option=active.options[Number(button.dataset.sentenceOption)];showLookup(button,option.zh);if(option.jp!==active.jp){void playChunkAnswer(option.audio,"wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");scheduleStage(()=>button.classList.remove("wrong"),520,version);return}chosen[current]=active;current+=1;const completeNow=current===item.groups.length;const playback=playChunkAnswer(option.audio,"correct");draw(completeNow,false);if(completeNow)void playback.then(completed=>completed&&version===stageVersion?playAudio(targetAudio,false,1,"npc"):false).then(completed=>{if(completed&&version===stageVersion){draw(true,true);playAudio(item.dialogue?.audio,false,1,"npc")}})}))};draw();
    }
    function renderOralFallback(index){
      const item=sentences[index],options=[...item.groups,...item.distractors].sort(()=>Math.random()-.5),selected=item.groups.map(()=>null);let current=0;
      const version=stageVersion,targetAudio=item.followAudio;const draw=(complete=false,showDialogue=item.dialoguePosition!=="after")=>{if(complete){stageEl.innerHTML=`${sceneBackdrop(item,showDialogue,"follow")}<section class="board" style="margin-top:2px">${completeHTML(item.groups,targetAudio,[],false,"npc")}</section>`;bindAudio();bindLookups();wireContinue();return}stageEl.innerHTML=`${sceneBackdrop(item,showDialogue,"follow")}<section class="board sentence-board" style="margin-top:2px"><p class="sentence-instruction">选择日语 chunk，完成中文提示：</p><div class="slots">${item.groups.map((group,groupIndex)=>`<div class="slot-unit"><div class="slot ${group.wide?"wide":""} ${selected[groupIndex]?"correct":""}">${selected[groupIndex]?`<button class="slot-button" type="button" data-lookup="${group.zh}" data-lookup-audio="${group.audio}" data-lookup-voice="machine" aria-label="${group.jp}"><span>${chunkBody(group.jp)}</span></button>`:`<button class="slot-hint lookup" type="button" data-lookup="${group.jp}" data-lookup-audio="${group.audio}" data-lookup-voice="machine">${group.zh}</button>`}</div>${chunkPunctuation(group.jp)}</div>`).join("")}</div><div class="pool review-pool">${options.map((option,optionIndex)=>`<button class="pill ${option.wide?"wide":""} ${selected.includes(option)?"used":""}" type="button" data-review-index="${optionIndex}" aria-label="${option.jp}"><span>${chunkBody(option.jp)}</span></button>`).join("")}</div></section>`;bindAudio();bindLookups();stageEl.querySelectorAll("[data-review-index]").forEach(button=>button.addEventListener("click",()=>{const option=options[Number(button.dataset.reviewIndex)];showLookup(button,option.zh);if(option.jp!==item.groups[current].jp){void playChunkAnswer(option.audio,"wrong");button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");scheduleStage(()=>button.classList.remove("wrong"),560,version);return}selected[current]=option;current+=1;const completeNow=current===item.groups.length;const playback=playChunkAnswer(option.audio,"correct");draw(completeNow,false);if(completeNow)void playback.then(completed=>completed&&version===stageVersion?playAudio(targetAudio,false,1,"npc"):false).then(completed=>{if(completed&&version===stageVersion){draw(true,true);playAudio(item.dialogue?.audio,false,1,"npc")}})}))};draw();
    }
    const escapeHTML=text=>String(text).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
    const speechText=text=>String(text).replace(/[\s、。！？,.（）()「」『』笑泣]/g,"");
    function speechScore(expected,actual){const left=speechText(expected),right=speechText(actual);if(!left||!right)return null;const row=Array.from({length:right.length+1},(_,index)=>index);for(let i=1;i<=left.length;i+=1){let previous=row[0];row[0]=i;for(let j=1;j<=right.length;j+=1){const saved=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(left[i-1]===right[j-1]?0:1));previous=saved}}return Math.max(0,Math.round((1-row[right.length]/Math.max(left.length,right.length))*100))}
    function renderFollow(index){
      const item=sentences[index],Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
      const version=stageVersion,targetAudio=item.followAudio,oralAlwaysPass=CONFIG.testing?.oralAlwaysPass===true;let transcript="",recognition=null,startedAt=0,elapsed=0,autoPlayed=false,oralError="",settled=false,dialogueRevealed=item.dialoguePosition!=="after";
      const targetHTML=()=>item.groups.map((group,index)=>`<button class="follow-chunk lookup" type="button" data-chunk-index="${index}" data-lookup="${group.zh}" data-lookup-audio="${group.audio}" data-lookup-voice="machine">${chunkBody(group.jp)}</button>${chunkPunctuation(group.jp)}`).join("");
      const translationHTML=()=>{const groups=item.groups,chunks=[{zh:"不用担心，",group:groups[0]},{zh:"因为",group:groups[3]},{zh:"我",group:groups[1]},{zh:`是${groups[2].zh}。`,group:groups[2]}];return chunks.map((chunk,index)=>`<button class="follow-translation-chunk lookup" type="button" data-chunk-index="${index}" data-lookup="${chunk.group.jp}" data-lookup-audio="${chunk.group.audio}" data-lookup-voice="machine">${chunk.zh}</button>`).join("")};
      const stopRecording=()=>{window.clearInterval(activeRecordTimer);activeRecordTimer=null;if(recognition){try{recognition.stop()}catch{}}};
      const drawRecord=(state="idle")=>{
        if(version!==stageVersion)return;
        const score=transcript?speechScore(item.jp,transcript):null,passed=state==="done"&&(oralAlwaysPass||(score!==null&&score>=CONFIG.audio.passScore));
        const result=state==="done"?`<div class="oral-result ${passed?"correct":"wrong"}"><div class="oral-verdict">${passed?"发音正确":"发音还不太对"}</div><div class="oral-transcript">${oralAlwaysPass?"测试模式：录音已完成":`识别结果：${transcript?escapeHTML(transcript):"未识别到有效语音"}`}</div>${!oralAlwaysPass&&score!==null?`<div class="oral-score">匹配度 ${score}%</div>`:""}</div>${passed?"":`<button class="oral-retry" type="button" data-retry>重新朗读</button>`}`:"";
        const error=state==="error"?`<div class="oral-error">${oralError}</div><button class="oral-retry" type="button" data-retry>重新尝试</button>`:"";
        stageEl.innerHTML=`${sceneBackdrop(item,dialogueRevealed,"follow")}<section class="board oral-board" style="margin-top:2px"><div class="follow-card"><p class="follow-title">请跟读：</p><div class="follow-japanese-row"><div class="follow-audio">${audioButton(targetAudio,false,1,"npc")}${audioButton(targetAudio,true,1,"npc")}</div><div class="follow-target">${targetHTML()}</div></div><div class="follow-translation">${translationHTML()}</div></div>${state==="idle"||state==="recording"?`<div class="record-area"><button class="record-button ${state==="recording"?"recording":""}" type="button" data-record aria-label="${state==="recording"?"停止录音":"开始录音"}">${state==="recording"?"■":"🎙"}</button><div class="record-copy">${state==="recording"?"点击结束":"点击录音"}</div>${state==="recording"?`<div class="record-timer" data-record-timer>${elapsed.toFixed(1)}s</div>`:""}</div>`:""}${result}${error}${state==="idle"?`<button class="skip-button" type="button" data-skip>现在不做口语题</button>`:""}</section>`;
        bindAudio();
        bindLookups();
        if(state==="idle"&&!autoPlayed){autoPlayed=true;playAudio(targetAudio,false,1,"npc")}
        stageEl.querySelector("[data-record]")?.addEventListener("click",()=>state==="recording"?stopRecording():startRecording());
        stageEl.querySelector("[data-retry]")?.addEventListener("click",()=>{transcript="";elapsed=0;settled=false;drawRecord("idle")});
        stageEl.querySelector("[data-skip]")?.addEventListener("click",()=>{oralMode="chunks";clearStageActivity();renderOralFallback(index)});
        if(state==="done")playFeedback(passed?"correct":"wrong");
      };
      async function startRecording(){
        if(!Recognition){oralError="当前浏览器不支持日语语音识别，请使用 Chrome 或 Edge 打开本页。";drawRecord("error");return}
        stopAudio();
        transcript="";settled=false;recognition=new Recognition();activeRecognition=recognition;recognition.lang="ja-JP";recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=3;
        recognition.onresult=event=>{transcript=Array.from(event.results).map(result=>result[0].transcript).join("")};
        recognition.onerror=event=>{if(settled||version!==stageVersion)return;if(oralAlwaysPass&&event.error!=="not-allowed"&&event.error!=="service-not-allowed"){settled=true;activeRecognition=null;window.clearInterval(activeRecordTimer);activeRecordTimer=null;drawRecord("done");scheduleStage(()=>playAudio(targetAudio,false,1,"npc").then(completed=>{if(!completed||version!==stageVersion)return false;dialogueRevealed=true;drawRecord("done");return playAudio(item.dialogue?.audio,false,1,"npc")}).then(completed=>{if(completed&&version===stageVersion)scheduleStage(nextStage,650,version)}),180,version);return}settled=true;activeRecognition=null;window.clearInterval(activeRecordTimer);activeRecordTimer=null;oralError=event.error==="not-allowed"||event.error==="service-not-allowed"?"麦克风权限被拒绝了，请允许权限后重试。":"没有识别到有效语音，请靠近麦克风再试一次。";drawRecord("error")};
        recognition.onend=()=>{if(settled||version!==stageVersion)return;settled=true;activeRecognition=null;window.clearInterval(activeRecordTimer);activeRecordTimer=null;drawRecord("done");if(transcript||oralAlwaysPass)scheduleStage(()=>playAudio(targetAudio,false,1,"npc").then(completed=>{if(!completed||version!==stageVersion)return false;dialogueRevealed=true;drawRecord("done");return playAudio(item.dialogue?.audio,false,1,"npc")}).then(completed=>{const passed=oralAlwaysPass||(speechScore(item.jp,transcript)??0)>=CONFIG.audio.passScore;if(completed&&passed&&version===stageVersion)scheduleStage(nextStage,650,version)}),180,version)};
        try{elapsed=0;startedAt=Date.now();recognition.start();drawRecord("recording");activeRecordTimer=window.setInterval(()=>{elapsed=(Date.now()-startedAt)/1000;const timer=stageEl.querySelector("[data-record-timer]");if(timer)timer.textContent=`${elapsed.toFixed(1)}s`;if(elapsed>=15)stopRecording()},100)}catch{activeRecognition=null;oralError="无法启动语音识别，请刷新页面后重试。";drawRecord("error")}
      }
      drawRecord();
    }
    function nextStage(){stageIndex+=1;if(stageIndex>=stages.length){clearStageActivity();showScreen(finishScreen);return}renderStage()}
    function renderStage(){clearStageActivity();window.scrollTo(0,0);const current=stages[stageIndex];progressFill.style.width=`${(stageIndex+1)/stages.length*100}%`;if(current.type==="meaning")renderMeaning(current.index);if(current.type==="spellWord")renderSpelling(vocab[current.index],"word");if(current.type==="spellPhrase")renderSpelling(vocab[current.index],"phrase");if(current.type==="sentence")renderSentence(current.index);if(current.type==="follow")(oralMode==="chunks"?renderOralFallback:renderFollow)(current.index)}
    function openJumpPicker(){jumpGrid.innerHTML=stages.map((_,index)=>`<button class="jump-option ${index===stageIndex?"selected":""}" type="button" data-jump-index="${index}">${index+1}</button>`).join("");jumpOverlay.hidden=false;jumpGrid.querySelectorAll("[data-jump-index]").forEach(button=>button.addEventListener("click",()=>{stageIndex=Number(button.dataset.jumpIndex);jumpOverlay.hidden=true;renderStage()}))}
    document.querySelector("#startButton").addEventListener("click",()=>{stageIndex=0;oralMode="speech";renderStage();showScreen(lessonScreen)});document.querySelector("#closeButton").addEventListener("click",()=>{clearStageActivity();showScreen(startScreen)});document.querySelector("#restartButton").addEventListener("click",()=>{stageIndex=0;oralMode="speech";renderStage();showScreen(lessonScreen)});progressTrack.addEventListener("click",openJumpPicker);document.querySelector("#jumpClose").addEventListener("click",()=>{jumpOverlay.hidden=true});jumpOverlay.addEventListener("click",event=>{if(event.target===jumpOverlay)jumpOverlay.hidden=true});
    const previewStage=Number(new URLSearchParams(window.location.search).get("stage"));if(Number.isInteger(previewStage)&&previewStage>=1&&previewStage<=stages.length){stageIndex=previewStage-1;renderStage();showScreen(lessonScreen)}
